spring:
  application:
    name: es-study
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.0.60:1532:deporcl
    username: wsdj_hbnw
    password: wsdj_hbnw

  elasticsearch:
    rest:
      uris: http://124.222.193.26:9200