spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: oauth-server
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.193.26:8848
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://124.222.193.26:3306/oauth?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 7787

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml