server:
  port: 8050
  servlet:
    context-path: gateway
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: api-service-route
          uri: lb://provider
          predicates:
            - Path=/gateway/provider/**
          filters:
            - StripPrefix=2
    nacos:
      discovery:
        server-addr: 124.222.193.26
