server:
  port: 8080

spring:
  application:
    name: jwt-demo
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://124.222.193.26:3306/nacos?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 124.222.193.26

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

token:
  expire: 360000
  key: 123456